# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickDroneMap
                                 A QGIS plugin
 todo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-24
        copyright            : (C) 2018 by Olivier Dalang / SPC
        email                : olivier.dalang@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QuickDroneMap class from file QuickDroneMap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .quick_drone_map import QuickDroneMap
    return QuickDroneMap(iface)
